### ISSUE TITLE
Further Milestones

### ISSUE THREAD

**Issue by larshilse** [GLINMACA/glinmaca.github.io#11]
What further milestones do we need to create for the post soft launch phase?

**Comment by spacemonkey** [comment]
I'd recommend creating two more releases, "Hard Launch" which is a fixed date and ties marketing and promotion to the actual launch, and "Backlog" which is where new stuff lives until it gets defined and added to a tracker for actual development in a build.

We can then add builds if we want, or just rely on git tags and releases to self document.

**Comment by spacemonkey** [comment]
Closing this issue out, setup the other two recommended milestones for now
