### ISSUE TITLE
Google groups vs. Slack 

### ISSUE THREAD

**Issue by larshilse** [GLINMACA/glinmaca.github.io#15]
Shall we gun for Google Groups rather than slack? People being more accustomed to the conventional style of discussion? 

Can we include it under top level menu under "discussion" and open in blank?

**Comment by larshilse** [comment]
I have also created a Google Groups account: https://groups.google.com/forum/#!forum/glinmaca

Just for integration into the website.

**Comment by spacemonkey** [comment]
Added menu for google group.
