### ISSUE TITLE
Outline top-level navigation

### ISSUE THREAD

**Issue by spacemonkey** [GLINMACA/glinmaca.github.io#3]
We can provide the list here in the tracker, and use that to generate the content pages for actual building of the website.

**Comment by larshilse** [comment]
(English version; translations are available accordingly in the language files on dropbox) 
- Introduction (Home)  
- Main Content (GLINMACA) 
- Contribute 
- About (Board, Translators, etc.) 
- Discuss (English only - Slack.com?) 
- Contact > Legal Info
