### ISSUE TITLE
Select layout/theme

### ISSUE THREAD

**Issue by spacemonkey** [GLINMACA/glinmaca.github.io#4]
Must be jekyll-compatible (or we could totally switch to something else like Hugo if the need arose).

**Comment by spacemonkey** [comment]
Can you take a look at http://jekyllthemes.org/ and pick one, then mention it here?

**Comment by larshilse** [comment]
If Kiko is more than just blogging, let's gun for that.

**Comment by larshilse** [comment]
Other than that: 
- http://scribble.muan.co/about/
- http://jekyllthemes.org/themes/emerald/ (if this can be made red, instead of emerald) 
- http://jekyllthemes.org/themes/so-simple/ (if the logo can be replaced) 
- http://jekyllthemes.org/themes/scribble/ (if the logo can be replaced)
