### ISSUE TITLE
Theme Selected

### ISSUE THREAD

**Issue by larshilse** [GLINMACA/glinmaca.github.io#8]
Other than that:

http://scribble.muan.co/about/
http://jekyllthemes.org/themes/emerald/ (if this can be made red, instead of emerald)
http://jekyllthemes.org/themes/so-simple/ (if the logo can be replaced)
http://jekyllthemes.org/themes/scribble/ (if the logo can be replaced)

**Comment by spacemonkey** [comment]
We have too many theme tracker items, what is the final decision? Happy to setup whatever is decided.

**Comment by spacemonkey** [comment]
Closing this out.
