### ISSUE TITLE
Top Level Navigation

### ISSUE THREAD

**Issue by larshilse** [GLINMACA/glinmaca.github.io#9]
(English version; translations are available accordingly in the language files on dropbox)
- Introduction (Home) --Multilang--
- Main Content (GLINMACA)--Multilang--
- Contribute--Multilang--
- Blog --EngOnly--
- About (Board, Translators, etc.) --EngOnly--
- Discuss (English only - Slack.com?) --EngOnly--
- Contact & Legal Info --EngOnly--

**Comment by spacemonkey** [comment]
Closing this out for now as all available things are linked.
